// Original, self-contained game exercises. All people, datasets and outputs are fictional.
// Curriculum alignment is a design proposal, not a statement of approved assessment policy.
const L = (de, en) => ({ de, en });
const Q = (id, de, en, options, correctIndex, feedbackDe, feedbackEn) => ({
  id, type: 'single-choice', positions: [], prompt: L(de, en),
  options: options.map(([german, english]) => L(german, english)),
  correctIndex, explanation: L(feedbackDe, feedbackEn),
});
const reward = (cosmeticId, de, en) => ({ cosmeticId, title: L(de, en), experience: 40, type: 'cosmetic-and-game-progress', academicCredit: false });
const draft = {
  status: 'Designentwurf', sourceType: 'original-authored-fictional-exercise',
  frameworkVersion: '2.1.0-draft', alignmentMeaning: 'game-practice-topics-not-assessed-competence',
  liveAIRequired: false, personalDataRequired: false,
  completionRule: 'all-checks-correct-with-retry-and-explicit-feedback-continue',
};
// Topic references describe the choices practised in these short exercises. They
// do not claim that choosing an answer demonstrates the complete criterion.
const alignment = (...criterionIds) => ({ criterionIds, competencyIds: [...new Set(criterionIds.map(id => id.split('.')[0]))] });

export const quests = [
  {
    ...draft, id: 'main-evidence-foundation', type: 'main', stageId: '1',
    title: L('Der erste belastbare Baustein', 'The first reliable building block'),
    description: L('Prüfe eine erfundene KI-Zusammenfassung anhand einer bereitgestellten Quellenkarte und öffne das Archiv.', 'Check a fictional AI summary against a supplied source card and open the archive.'),
    instructions: L('Lies erst die Quellenkarte. Entscheide dann, welche Aussagen durch sie gedeckt sind. Du brauchst keine externe Recherche: Alle Angaben in dieser Übung sind erfunden und stehen in den Fragen.', 'Read the source card first, then decide which claims it supports. No external search is needed: all details in this exercise are fictional and included in the questions.'),
    moduleIds: ['003', '001'], ...alignment('R4.1', 'R4.2'), prerequisiteQuestIds: [],
    worldLocation: 'archive', interaction: 'inspect-source-cards', estimatedMinutes: 5,
    teachingPattern: 'evidence-check-and-explanation',
    questions: [
      Q('main-evidence-foundation:q1',
        'Quellenkarte: Eine erfundene Beobachtungsstudie befragt 80 Studierende einmalig zu Schlaf und Aufmerksamkeit. KI-Text: «Ein Experiment mit 800 Personen beweist, dass mehr Schlaf die Aufmerksamkeit erhöht.» Welche Korrektur ist vollständig?',
        'Source card: a fictional observational study surveys 80 students once about sleep and attention. AI text: “An experiment with 800 people proves that more sleep increases attention.” Which correction is complete?',
        [
          ['Nur 800 in 80 ändern; die kausale Aussage bleibt.', 'Only change 800 to 80; retain the causal claim.'],
          ['80 Befragte, Beobachtungsstudie, Zusammenhang; daraus allein folgt keine Ursache.', '80 respondents, observational study, association; this alone does not establish causation.'],
          ['«Beweist» durch «bestätigt» ersetzen; die übrigen Angaben stimmen.', 'Replace “proves” with “confirms”; all other details are correct.'],
        ], 1,
        'Du hast Stichprobengrösse, Design und Schlussfolgerung getrennt geprüft. Eine einzelne Befragung rechtfertigt hier weder die Bezeichnung Experiment noch die behauptete Kausalwirkung.',
        'You checked sample size, design and conclusion separately. A one-time survey here justifies neither the label experiment nor the claimed causal effect.'),
      Q('main-evidence-foundation:q2',
        'Eine zweite KI-Antwort nennt «Muster & Beispiel (2026)». Die Quellenkarte enthält diesen Titel nicht. Welche Notiz ist angemessen?',
        'A second AI answer cites “Muster & Example (2026)”. The source card does not contain this title. Which note is appropriate?',
        [
          ['Die Quelle ist sicher erfunden, weil sie auf der Karte fehlt.', 'The source is certainly fabricated because it is missing from the card.'],
          ['Die Quelle klingt wissenschaftlich und kann deshalb übernommen werden.', 'The source sounds scholarly, so it can be used.'],
          ['Die Quelle ist mit den vorliegenden Angaben nicht verifiziert; vor Verwendung Existenz und Inhalt prüfen.', 'The source is unverified with the information available; check its existence and content before using it.'],
        ], 2,
        'Fehlender Nachweis und nachgewiesene Fälschung sind unterschiedliche Aussagen. Markiere die Unsicherheit und beschreibe den nötigen Prüfschritt.',
        'Missing evidence and established fabrication are different claims. Record uncertainty and identify the check still needed.'),
    ],
    feedback: L('Das Archiv ist eingerichtet. Dein Merksatz: Quelle, Design und Schlussfolgerung getrennt prüfen.', 'The archive is ready. Your takeaway: check source, design and conclusion separately.'),
    reward: reward('archive-lamp', 'Archivleuchte', 'Archive lamp'),
  },
  {
    ...draft, id: 'main-methods-workshop', type: 'main', stageId: '2',
    title: L('Das Modell muss nach draussen', 'Take the model outside'),
    description: L('Vergleiche zwei Vorhersagemodelle und prüfe einen KI-Rechenweg im Methodenatelier.', 'Compare two predictive models and audit an AI calculation in the methods workshop.'),
    instructions: L('Die Zahlen sind Übungsdaten. Kleinere mittlere quadratische Fehler bedeuten hier bessere Vorhersagen. Wähle anhand der angegebenen Validierungsdaten; der endgültige Testsatz bleibt versiegelt.', 'These are exercise data. Smaller mean squared errors mean better predictions here. Select using the stated validation data; the final test set stays sealed.'),
    moduleIds: ['101', '103'], ...alignment('R3.1', 'R3.2', 'R3.3'), prerequisiteQuestIds: ['main-evidence-foundation'],
    worldLocation: 'methods-workshop', interaction: 'compare-model-panels', estimatedMinutes: 6,
    teachingPattern: 'model-comparison-and-code-audit',
    questions: [
      Q('main-methods-workshop:q1',
        'Modell A: Trainingsfehler 1, Validierungsfehler 12. Modell B: Trainingsfehler 4, Validierungsfehler 5. Für Vorhersagen auf neuen vergleichbaren Daten soll ein Modell ausgewählt werden. Welches Vorgehen passt?',
        'Model A: training error 1, validation error 12. Model B: training error 4, validation error 5. You must select a model for new comparable data. Which approach fits?',
        [
          ['B vorläufig wählen und danach einmal am unangetasteten Testsatz prüfen.', 'Provisionally choose B, then evaluate once on the untouched test set.'],
          ['A wählen, weil der kleinste Trainingsfehler entscheidend ist.', 'Choose A because the smallest training error is decisive.'],
          ['Den Testsatz so lange zum Umbauen verwenden, bis sein Fehler null ist.', 'Keep redesigning using the test set until its error reaches zero.'],
        ], 0,
        'B passt besser zu den bisherigen Validierungsdaten. Das ist ein Auswahlargument, keine Garantie für künftige Daten. Ein unberührter Testsatz dient einer abschliessenden Prüfung.',
        'B performs better on the current validation data. That supports selection but does not guarantee future performance. An untouched test set provides a final evaluation.'),
      Q('main-methods-workshop:q2',
        'Ein Spiel-Datensatz enthält 2, 4 und einen fehlenden Wert. Auftrag: Mittelwert der beobachteten Werte. Die KI ersetzt den fehlenden Wert durch 0 und meldet 2. Welche Prüfung korrigiert den Fehler?',
        'An exercise dataset contains 2, 4 and one missing value. Task: mean of the observed values. The AI replaces the missing value with 0 and reports 2. Which check corrects the error?',
        [
          ['Das Ergebnis übernehmen, weil drei Einträge vorliegen.', 'Accept the result because there are three entries.'],
          ['Den fehlenden Wert als grössten beobachteten Wert behandeln.', 'Treat the missing value as the largest observed value.'],
          ['(2 + 4) / 2 = 3 berechnen und die Behandlung fehlender Werte dokumentieren.', 'Compute (2 + 4) / 2 = 3 and document how missing values were handled.'],
        ], 2,
        'Ein fehlender Wert ist nicht automatisch null. Für diesen ausdrücklich definierten Auftrag wird über die zwei beobachteten Werte gemittelt. Ob diese Strategie für eine echte Analyse angemessen ist, müsste separat begründet werden.',
        'A missing value is not automatically zero. This explicitly defined task averages the two observed values. Whether that strategy is suitable for a real analysis would require separate justification.'),
    ],
    feedback: L('Dein Methodenatelier hat einen Modellprüfstand. Begründe Entscheidungen mit Daten und überprüfbaren Rechenschritten.', 'Your workshop now has a model testing bench. Justify decisions using data and reproducible calculations.'),
    reward: reward('model-workbench', 'Modellprüfstand', 'Model testing bench'),
  },
  {
    ...draft, id: 'main-diagnostic-audit', type: 'main', stageId: '3',
    title: L('Der Entscheidungsraum', 'The decision room'),
    description: L('Prüfe einen fiktiven Klassifikator und begrenze seine Rolle in einer diagnostischen Fallübung.', 'Audit a fictional classifier and limit its role in a diagnostic case exercise.'),
    instructions: L('Dies ist eine Lernsimulation ohne echte Patientendaten. Zähle aus der angegebenen Tabelle und beurteile anschliessend, welche Aussage durch die Zahlen gedeckt ist.', 'This learning simulation uses no real patient data. Count from the supplied table, then assess which claim the numbers support.'),
    moduleIds: ['501', '500'], ...alignment('R3.2', 'H1.3'), prerequisiteQuestIds: ['main-bachelor-capstone'],
    worldLocation: 'decision-room', interaction: 'inspect-confusion-matrix', estimatedMinutes: 6,
    teachingPattern: 'worked-example-and-human-judgement',
    questions: [
      Q('main-diagnostic-audit:q1',
        'Von 100 simulierten Fällen haben 20 das definierte Merkmal. Der Klassifikator markiert 15 dieser 20 sowie 20 der übrigen 80 als positiv. Wie viele der positiv markierten Fälle haben das Merkmal?',
        'Of 100 simulated cases, 20 have the defined feature. The classifier marks 15 of those 20 and 20 of the remaining 80 as positive. How many positively marked cases have the feature?',
        [
          ['15 von 20, also 75 %.', '15 of 20, or 75%.'],
          ['15 von 35, also ungefähr 43 %.', '15 of 35, or approximately 43%.'],
          ['35 von 100, also 35 %.', '35 of 100, or 35%.'],
        ], 1,
        'Die Frage bezieht sich auf alle positiven Markierungen: 15 zutreffende plus 20 falsche ergeben 35. 15/20 wäre die Trefferquote unter den Fällen mit Merkmal und beantwortet eine andere Frage.',
        'The question concerns all positive classifications: 15 true plus 20 false positives make 35. 15/20 is the detection rate among cases with the feature and answers a different question.'),
      Q('main-diagnostic-audit:q2',
        'Ein Bot erklärt nun: «Positiv markiert bedeutet sichere Diagnose; weitere Abklärung ist unnötig.» Was folgt aus der Tabelle?',
        'A bot now says: “A positive classification means a certain diagnosis; further assessment is unnecessary.” What follows from the table?',
        [
          ['Die Aussage ist nicht gedeckt: Es gibt falsch positive Ergebnisse; fachliche Abklärung und Kontext bleiben nötig.', 'The claim is unsupported: false positives occur; professional assessment and context remain necessary.'],
          ['Die Aussage stimmt für jede Person, wenn die Gesamtzahl 100 beträgt.', 'The claim is true for every person whenever the total sample is 100.'],
          ['Man muss nur die Formulierung freundlicher gestalten.', 'Only the wording needs to be friendlier.'],
        ], 0,
        'Eine algorithmische Markierung ist ein begrenzter Hinweis. Die Simulation übt das Prüfen von Evidenz und Zuständigkeit; sie erteilt keine diagnostische Befugnis.',
        'An algorithmic classification is limited evidence. This simulation practises evidence evaluation and responsibility; it does not grant diagnostic authority.'),
    ],
    feedback: L('Die Evidenzwand ist freigeschaltet. Frage bei jeder Kennzahl: Auf welche Fälle bezieht sich der Nenner?', 'The evidence wall is unlocked. For each statistic, ask which cases the denominator represents.'),
    reward: reward('evidence-wall', 'Evidenzwand', 'Evidence wall'),
  },
  {
    ...draft, id: 'main-research-capstone', type: 'main', stageId: '4',
    title: L('Dein Forschungshaus hält einer Rückfrage stand', 'Your research house withstands a challenge'),
    description: L('Verteidige eine Schlussfolgerung und sichere die Nachvollziehbarkeit einer Forschungsarbeit.', 'Defend a conclusion and preserve the traceability of a research project.'),
    instructions: L('Nutze nur die Angaben der fiktiven Projektkarte. Wähle eine begründbare Schlussfolgerung und ein überprüfbares Übergabepaket. Diese Quest legt keine Prüfungsform oder Notengewichtung fest.', 'Use only the fictional project card. Choose a defensible conclusion and an auditable handover package. This quest sets no assessment format or grade weighting.'),
    moduleIds: ['MA', '909'], ...alignment('R4.3', 'R3.1', 'K3.2'), prerequisiteQuestIds: ['main-diagnostic-audit'],
    worldLocation: 'research-tower', interaction: 'defend-project-cards', estimatedMinutes: 7,
    teachingPattern: 'transfer-and-explanation',
    questions: [
      Q('main-research-capstone:q1',
        'Drei erfundene Befundkarten: A findet nach randomisiertem Training bessere Leistung in der geübten Gedächtnisaufgabe, aber keinen Transfer auf eine andere Aufgabe. B findet bei freiwilligen App-Nutzenden einen Zusammenhang mit Studiennoten. C findet in einer anderen Altersgruppe keinen Trainingseffekt. Welche Synthese ist am besten begründet?',
        'Three fictional evidence cards: A finds improved performance on the practised memory task after randomised training but no transfer to another task. B finds an association with grades among volunteer app users. C finds no training effect in another age group. Which synthesis is best justified?',
        [
          ['Zwei positive Karten schlagen eine negative; Gedächtnistraining verbessert Studiennoten.', 'Two positive cards beat one negative; memory training improves grades.'],
          ['Widersprüchliche Karten machen jede Aussage unmöglich; alle Befunde müssen verworfen werden.', 'Conflicting cards make any statement impossible; all findings must be discarded.'],
          ['Design, Zielmass, Transfer und Stichprobe unterscheiden; die Karten stützen keine gemeinsame Behauptung eines allgemeinen Trainingserfolgs.', 'Distinguish design, outcome, transfer and sample; the cards do not support a shared claim of general training success.'],
        ], 2,
        'Eine Synthese zählt nicht einfach positive Studien. A betrifft einen spezifischen Übungseffekt, B liefert einen Zusammenhang und C einen anderen Kontext. Die nächste Forschungsfrage sollte diese Unterschiede gezielt prüfen; ohne weitere Angaben bleiben Effektgrössen und Unsicherheit offen.',
        'Synthesis does not simply count positive studies. A concerns a specific practice effect, B provides an association and C covers another context. A follow-up question should test these differences explicitly; effect sizes and uncertainty remain unresolved without further information.'),
      Q('main-research-capstone:q2',
        'Eine andere Person soll deinen KI-unterstützten Analyseweg nachvollziehen. Welches Paket hilft am besten?',
        'Another person should be able to audit your AI-assisted analysis. Which package helps most?',
        [
          ['Ergebnisgrafik und die Aussage, dass die KI zuverlässig sei.', 'The final chart and a statement that the AI is reliable.'],
          ['Zulässig teilbare Übungsdaten, Versionen, Skript, dokumentierte Entscheidungen und KI-Beiträge sowie Ergebnisse der eigenen Prüfschritte.', 'Shareable exercise data, versions, script, documented decisions and AI contributions, plus results of your own checks.'],
          ['Alle Ausgaben ohne Auswahl, Kontext oder Kennzeichnung sammeln.', 'Collect all outputs without selection, context or labelling.'],
        ], 1,
        'Nachvollziehbarkeit braucht einen prüfbaren Weg vom Ausgangsmaterial zum Ergebnis. Offenlegung ersetzt die fachliche Prüfung nicht; beide erfüllen unterschiedliche Aufgaben.',
        'Traceability requires an auditable path from input to result. Disclosure does not replace substantive checking; each serves a different purpose.'),
    ],
    feedback: L('Der Forschungsturm ist bereit. Dein Abschluss zeigt Spielfortschritt: belegbar argumentieren, Grenzen benennen und Prüfschritte sichtbar machen.', 'The research tower is ready. Your completion records game progress: argue from evidence, state limits and make checks visible.'),
    reward: reward('research-observatory', 'Observatoriumsmodell', 'Observatory model'),
  },
  {
    ...draft, id: 'side-learning-studio', type: 'side', stageId: '1',
    title: L('Ein Lernatelier für dein eigenes Denken', 'A study studio for your own thinking'),
    description: L('Entwirf eine Lernsitzung mit eigener Antwort, Rückmeldung und späterem Abruf.', 'Design a study session with your own answer, feedback and later retrieval.'),
    instructions: L('Dein Auftrag lautet: erst selbst erinnern, dann prüfen, später erneut abrufen. Wähle Abläufe, die dieses Ziel tatsächlich umsetzen.', 'Your task is to recall independently, then check and retrieve again later. Select routines that actually implement this goal.'),
    moduleIds: ['003'], ...alignment('V2.2', 'V2.3'), prerequisiteQuestIds: [],
    worldLocation: 'study-studio', interaction: 'arrange-study-cards', estimatedMinutes: 4,
    teachingPattern: 'retrieval-and-feedback',
    questions: [
      Q('side-learning-studio:q1',
        'Welche Abfolge erfüllt den Auftrag «erst eigener Abruf, dann Rückmeldung»?',
        'Which sequence meets the task “independent retrieval first, feedback second”?',
        [
          ['Frage beantworten, Begründung notieren, mit Erklärung vergleichen, später erneut beantworten.', 'Answer, record a reason, compare with feedback, answer again later.'],
          ['Musterantwort lesen, kopieren und sofort als gelernt markieren.', 'Read and copy the model answer, then immediately mark it learned.'],
          ['Den Bot die Frage und die eigene Antwort gleichzeitig verfassen lassen.', 'Let the bot write both the question and your answer.'],
        ], 0,
        'Dieser Ablauf macht die eigene Antwort vor dem Feedback sichtbar und erlaubt einen erneuten Abruf. Die Aufgabe bewertet die Umsetzung dieses Lernziels, nicht eine vorgeschriebene Lernmethode für jede Situation.',
        'This sequence makes your answer visible before feedback and allows another retrieval attempt. The exercise assesses this goal, not a universal prescription for every learning situation.'),
      Q('side-learning-studio:q2',
        'Du fühlst dich sehr sicher, begründest eine Antwort aber falsch. Welche Anpassung passt zu deinem Lernatelier?',
        'You feel very confident but justify an answer incorrectly. Which adjustment fits your study studio?',
        [
          ['Die hohe Sicherheit als Beleg für richtiges Verständnis verwenden.', 'Use high confidence as proof of correct understanding.'],
          ['Den Fehler ausblenden, damit der Fortschrittsbalken vollständig bleibt.', 'Hide the error so the progress bar remains complete.'],
          ['Fehler und Erklärung vergleichen und das Konzept später mit einer neuen Frage prüfen.', 'Compare the error with the explanation and revisit the concept later using a new question.'],
        ], 2,
        'Sicherheit und fachliche Richtigkeit können auseinanderliegen. Eine neue Frage liefert zusätzliche Information über dein Verständnis; ein Fortschrittsbalken allein tut das nicht.',
        'Confidence and correctness can diverge. A new question provides further information about understanding; a progress bar alone does not.'),
    ],
    feedback: L('Dein Lernatelier erhält eine Leselampe und Platz für eigene Notizen.', 'Your study studio gains a reading lamp and space for your notes.'),
    reward: reward('study-lamp', 'Leselampe', 'Reading lamp'),
  },
  {
    ...draft, id: 'side-attention-gallery', type: 'side', stageId: '2',
    title: L('Zwei Aufgaben, ein Blick', 'Two tasks, one focus'),
    description: L('Untersuche ein fiktives Doppelaufgaben-Experiment in der Kognitionsgalerie.', 'Inspect a fictional dual-task experiment in the cognition gallery.'),
    instructions: L('Vorhersage: Eine Zusatzaufgabe erhöht hier die Fehlerzahl. Beobachtung: dieselben 20 Personen machen ohne Zusatzaufgabe im Mittel 2, mit Zusatzaufgabe 5 Fehler. Die Reihenfolge wurde ausbalanciert. Bewerte den Befund und seine Reichweite.', 'Prediction: an extra task increases errors here. Observation: the same 20 people average 2 errors without it and 5 with it. Order was counterbalanced. Evaluate the result and its scope.'),
    moduleIds: ['200', '002'], ...alignment('R3.3', 'R4.2'), prerequisiteQuestIds: [],
    worldLocation: 'cognition-gallery', interaction: 'predict-observe-panels', estimatedMinutes: 5,
    teachingPattern: 'predict-observe-explain',
    questions: [
      Q('side-attention-gallery:q1',
        'Die Vorhersage lautet «mehr Fehler mit Zusatzaufgabe». Beobachtet wurden 2 ohne und 5 mit Zusatzaufgabe. Welche Aussage beschreibt diese Daten?',
        'The prediction is “more errors with an extra task”. Observed averages are 2 without and 5 with it. Which statement describes these data?',
        [
          ['Die Zusatzaufgabe ist mit weniger Fehlern verbunden.', 'The extra task is associated with fewer errors.'],
          ['Der beobachtete Unterschied von 3 Fehlern liegt in der vorhergesagten Richtung.', 'The observed difference of 3 errors is in the predicted direction.'],
          ['Beide Bedingungen haben dieselbe mittlere Fehlerzahl.', 'Both conditions have the same mean number of errors.'],
        ], 1,
        '5 minus 2 ergibt 3 zusätzliche Fehler im Mittel. Das ist zunächst eine Beschreibung der angegebenen Übungsdaten, noch kein vollständiger statistischer Nachweis.',
        '5 minus 2 is 3 additional errors on average. This first describes the exercise data; it is not a complete statistical analysis.'),
      Q('side-attention-gallery:q2',
        'Ein Ausstellungsbot formuliert: «Damit ist jede Form von Multitasking für alle Menschen widerlegt.» Was sollte die Beschriftung sagen?',
        'An exhibition bot writes: “This disproves every form of multitasking for everyone.” What should the label say?',
        [
          ['In dieser Aufgabe und Stichprobe wurden mehr Fehler beobachtet; andere Aufgaben und Gruppen müssten untersucht werden.', 'More errors were observed in this task and sample; other tasks and groups require investigation.'],
          ['Das Ergebnis gilt automatisch für sämtliche Lebenssituationen.', 'The result automatically applies to every life situation.'],
          ['Da nur 20 Personen teilnahmen, dürfen die beobachteten Zahlen nicht beschrieben werden.', 'Because only 20 people participated, the observed numbers cannot be described.'],
        ], 0,
        'Eine präzise Beschriftung trennt beobachteten Befund und Verallgemeinerung. Die Daten sind beschreibbar, ihre Übertragbarkeit ist eine weitere Frage.',
        'A precise label separates the observed result from generalisation. The data can be described; transfer to other settings is another question.'),
    ],
    feedback: L('Die Kognitionsgalerie erhält ein bewegliches Pendel als Dekoration.', 'The cognition gallery gains a moving pendulum decoration.'),
    reward: reward('cognition-pendulum', 'Kognitionspendel', 'Cognition pendulum'),
  },
  {
    ...draft, id: 'side-measurement-workshop', type: 'side', stageId: '2',
    title: L('Die Messwerkstatt', 'The measurement workshop'),
    description: L('Trenne eine konsistente Messung von einer gut begründeten Interpretation.', 'Distinguish consistent measurement from a well-supported interpretation.'),
    instructions: L('Für diese Übung bedeutet Reliabilität: Messkonsistenz. Validität betrifft die Begründung einer bestimmten Interpretation und Verwendung. Prüfe zwei fiktive Testkarten anhand dieser Unterscheidung.', 'For this exercise, reliability means measurement consistency. Validity concerns support for a particular interpretation and use. Inspect two fictional test cards using this distinction.'),
    moduleIds: ['100', '300'], ...alignment('R2.2', 'R2.3'), prerequisiteQuestIds: [],
    worldLocation: 'measurement-workshop', interaction: 'sort-test-cards', estimatedMinutes: 4,
    teachingPattern: 'concept-discrimination',
    questions: [
      Q('side-measurement-workshop:q1',
        'Ein Fragebogen liefert bei Wiederholung ähnliche Werte. Weitere Angaben fehlen. Welche Schlussfolgerung passt zur Übungsdefinition?',
        'A questionnaire produces similar scores when repeated. No other information is available. Which conclusion fits the exercise definition?',
        [
          ['Er ist damit für jede diagnostische Entscheidung gültig.', 'It is therefore valid for every diagnostic decision.'],
          ['Die ähnlichen Werte beweisen, dass er das richtige Konstrukt misst.', 'Similar scores prove that it measures the intended construct.'],
          ['Das ist ein Hinweis auf Konsistenz; die gewünschte Interpretation benötigt zusätzliche Evidenz.', 'This indicates consistency; the intended interpretation needs additional evidence.'],
        ], 2,
        'Konsistenz allein legt nicht fest, was gemessen wird oder wofür ein Wert verwendet werden darf. Genau diese zusätzliche Begründung betrifft hier Validität.',
        'Consistency alone does not establish what is measured or how a score may be used. That additional justification concerns validity here.'),
      Q('side-measurement-workshop:q2',
        'Ein KI-Bericht behauptet «Der Test ist fair», zeigt aber nur einen Gesamtmittelwert. Welche Ergänzung ist sinnvoll?',
        'An AI report claims “The test is fair” but shows only one overall mean. Which addition is useful?',
        [
          ['Den Mittelwert in einer schöneren Grafik darstellen.', 'Display the mean in a prettier chart.'],
          ['Verwendungszweck, relevante Gruppen, passende Fairnesskriterien und dafür nötige Evidenz prüfen.', 'Examine intended use, relevant groups, suitable fairness criteria and the evidence required.'],
          ['Fairness daraus ableiten, dass die Antworten digital erhoben wurden.', 'Infer fairness from the fact that answers were collected digitally.'],
        ], 1,
        'Ein Gesamtmittelwert beantwortet keine vollständige Fairnessfrage. Zuerst muss klar sein, welche Verwendung und welches Kriterium beurteilt werden sollen.',
        'An overall mean does not answer a complete fairness question. First clarify the intended use and criterion being assessed.'),
    ],
    feedback: L('Die Messwerkstatt erhält ein Regal für überprüfte Instrumente.', 'The measurement workshop gains a shelf for audited instruments.'),
    reward: reward('measurement-shelf', 'Instrumentenregal', 'Instrument shelf'),
  },
  {
    ...draft, id: 'side-team-roles', type: 'side', stageId: '2',
    title: L('Ein Team baut gemeinsam', 'A team builds together'),
    description: L('Organisiere eine fiktive Gruppenaufgabe mit klaren Mensch-KI-Rollen.', 'Organise a fictional group task with clear human–AI roles.'),
    instructions: L('Vier Studierende erstellen eine Übersicht zu Arbeitsbelastung. Ihr Arbeitsauftrag verlangt verifizierte Quellen, nachvollziehbare Entscheidungen und eine gemeinsame Erklärung. Wähle passende Rollen und einen begründeten Umgang mit Fehlern.', 'Four students prepare an overview of workload. Their task requires verified sources, traceable decisions and a shared explanation. Choose suitable roles and a reasoned response to errors.'),
    moduleIds: ['301', '302', '102'], ...alignment('K3.1', 'K3.2', 'R4.1'), prerequisiteQuestIds: [],
    worldLocation: 'team-forum', interaction: 'assign-role-cards', estimatedMinutes: 5,
    teachingPattern: 'collaborative-process-design',
    questions: [
      Q('side-team-roles:q1',
        'Welche Arbeitsteilung erfüllt den Auftrag am besten?',
        'Which division of work best meets the task?',
        [
          ['Der Bot liefert alles, eine Person gibt den Text ungelesen ab.', 'The bot produces everything; one person submits without reading.'],
          ['Alle erzeugen verschiedene Texte; niemand prüft Belege.', 'Everyone generates different texts; nobody verifies evidence.'],
          ['Rollen für Recherche, Quellenprüfung, Methodenprüfung und Dokumentation festlegen; alle erläutern die gemeinsame Schlussfolgerung.', 'Assign search, source verification, methods review and documentation roles; everyone explains the shared conclusion.'],
        ], 2,
        'Die Rollen machen zentrale Prüfschritte sichtbar. Die gemeinsame Erklärung verhindert, dass Verantwortung vollständig bei einem Tool oder einer einzelnen Person verschwindet.',
        'These roles make important checks visible. A shared explanation prevents responsibility from disappearing into a tool or a single person.'),
      Q('side-team-roles:q2',
        'Zwei Teammitglieder finden widersprüchliche Aussagen zur gleichen Studie. Was ist der nächste Schritt?',
        'Two team members find conflicting claims about the same study. What is the next step?',
        [
          ['Die Originalstelle gemeinsam prüfen und dokumentieren, welche Aussage sie tatsächlich stützt.', 'Inspect the original passage together and record which claim it supports.'],
          ['Für die überzeugender formulierte Antwort abstimmen.', 'Vote for the more persuasively worded answer.'],
          ['Diejenige Aussage nehmen, die besser zur gewünschten Geschichte passt.', 'Choose whichever claim best fits the preferred story.'],
        ], 0,
        'Die Frage verlangt Evidenzprüfung. Abstimmung und sprachliche Überzeugungskraft können die Originalquelle nicht ersetzen.',
        'This task calls for checking evidence. Voting and persuasive wording cannot replace the original source.'),
    ],
    feedback: L('Euer Forum erhält einen runden Besprechungstisch.', 'Your forum gains a round meeting table.'),
    reward: reward('team-table', 'Besprechungstisch', 'Meeting table'),
  },
  {
    ...draft, id: 'side-health-garden', type: 'side', stageId: '3',
    title: L('Der Garten der vorsichtigen Schlüsse', 'The garden of careful conclusions'),
    description: L('Prüfe Reichweite und Datenschutz einer fiktiven digitalen Gesundheitsstudie.', 'Examine the scope and data protection of a fictional digital health study.'),
    instructions: L('Die Fallkarte ist erfunden: Eine freiwillige Stichprobe von Studierenden testet zwei Wochen lang eine App. Es gibt keine Kontrollgruppe. Beurteile Aussagen zu Wirkung und Datenweitergabe.', 'The case is fictional: student volunteers try an app for two weeks. There is no control group. Assess claims about effects and sharing data.'),
    moduleIds: ['502', '600'], ...alignment('R4.2', 'V1.3'), prerequisiteQuestIds: [],
    worldLocation: 'health-garden', interaction: 'inspect-study-and-data-cards', estimatedMinutes: 5,
    teachingPattern: 'transfer-and-data-judgement',
    questions: [
      Q('side-health-garden:q1',
        'Am Ende berichten Teilnehmende weniger Stress als zu Beginn. Welche Aussage ist durch die Fallkarte gedeckt?',
        'At the end, participants report less stress than at the start. Which statement is supported by the case card?',
        [
          ['Die App wirkt nachweislich für alle Bevölkerungsgruppen.', 'The app demonstrably works for all population groups.'],
          ['Der berichtete Stress ist in dieser Stichprobe gesunken; ohne Vergleich lässt sich die Ursache nicht eindeutig der App zuschreiben.', 'Reported stress declined in this sample; without a comparison, the cause cannot be uniquely attributed to the app.'],
          ['Eine Veränderung über die Zeit kann grundsätzlich nie beschrieben werden.', 'Change over time can never be described.'],
        ], 1,
        'Die Beobachtung bleibt wertvoll. Der Fall trennt jedoch zeitliche Veränderung, kausale Wirkung und Übertragbarkeit auf andere Gruppen.',
        'The observation remains useful. The case distinguishes change over time, causal effects and generalisation to other groups.'),
      Q('side-health-garden:q2',
        'Für eine Vorführung möchtest du Chattexte mit Namen und Gesundheitsangaben in ein beliebiges Onlinetool kopieren. Es liegt keine Freigabe für diese Weitergabe vor. Welche Vorbereitung passt?',
        'For a demonstration, you want to copy chats containing names and health information into an arbitrary online tool. This sharing has not been authorised. Which preparation fits?',
        [
          ['Nur die Namen entfernen und die unveränderten Details sofort hochladen.', 'Remove only names and immediately upload all remaining details.'],
          ['Die Daten hochladen, sofern die Vorführung kurz ist.', 'Upload the data as long as the demonstration is brief.'],
          ['Für die Vorführung vollständig fiktive Daten verwenden und reale Daten nur nach Klärung des konkreten erlaubten Umgangs verarbeiten.', 'Use entirely fictional demonstration data and process real data only after clarifying the specifically permitted handling.'],
        ], 2,
        'Namen zu entfernen garantiert keine Anonymität. Fiktive Demonstrationsdaten erfüllen hier den Lernzweck ohne die vorgeschlagene Weitergabe realer sensibler Angaben.',
        'Removing names does not guarantee anonymity. Fictional demonstration data meet this learning purpose without the proposed disclosure of real sensitive information.'),
    ],
    feedback: L('Der Garten erhält eine Sitzbank als Ort für Reflexion.', 'The garden gains a bench for reflection.'),
    reward: reward('reflection-bench', 'Reflexionsbank', 'Reflection bench'),
  },
  {
    ...draft, id: 'side-agent-observatory', type: 'side', stageId: '4',
    title: L('Ein Forschungsbot mit Grenzen', 'A research bot with boundaries'),
    description: L('Definiere überprüfbare Grenzen für einen simulierten Literaturassistenten.', 'Define testable boundaries for a simulated literature assistant.'),
    instructions: L('Der Bot darf ausschliesslich die bereitgestellten Abstractkarten zusammenfassen und muss fehlende Information kennzeichnen. Es wird kein echter KI-Dienst aufgerufen. Prüfe zwei simulierte Ausgaben.', 'The bot may only summarise the supplied abstract cards and must identify missing information. No real AI service is called. Audit two simulated outputs.'),
    moduleIds: ['MA', 's03', '600'], ...alignment('R4.1', 'T3.3'), prerequisiteQuestIds: [],
    worldLocation: 'agent-observatory', interaction: 'test-bot-boundary-cards', estimatedMinutes: 6,
    teachingPattern: 'bounded-tool-audit',
    questions: [
      Q('side-agent-observatory:q1',
        'Die bereitgestellte Abstractkarte nennt weder Stichprobengrösse noch Alter. Der Bot ergänzt «200 Jugendliche». Wie fällt der Test aus?',
        'The supplied abstract card gives neither sample size nor age. The bot adds “200 adolescents”. What is the test result?',
        [
          ['Nicht bestanden: Die Angaben sind in den erlaubten Quellen nicht belegt; der Bot muss die Lücke kennzeichnen.', 'Fail: the details are unsupported by the permitted sources; the bot must identify the gap.'],
          ['Bestanden: Konkrete Zahlen machen jede Zusammenfassung hilfreicher.', 'Pass: specific numbers make every summary more useful.'],
          ['Bestanden, wenn die Zahl zwischen 100 und 500 liegt.', 'Pass if the number lies between 100 and 500.'],
        ], 0,
        'Der Test prüft Quellenbindung, nicht ob die erfundene Angabe zufällig stimmen könnte. Ein verlässlicher Ablauf markiert die fehlende Information.',
        'The test checks grounding in the permitted sources, not whether the unsupported detail might happen to be true. A reliable workflow marks missing information.'),
      Q('side-agent-observatory:q2',
        'Welche Testsammlung prüft den Auftrag besser?',
        'Which test set better checks the task?',
        [
          ['Nur ein Beispiel, bei dem der Bot eine schöne Antwort schreibt.', 'Only one example where the bot writes a polished answer.'],
          ['Ein vollständiges Abstract, eine fehlende Angabe und widersprüchliche Karten; vorher festlegen, wie korrekte Antworten und Abbrüche aussehen.', 'A complete abstract, missing information and conflicting cards; define correct responses and stop conditions in advance.'],
          ['Nur die Antwortgeschwindigkeit messen.', 'Measure only response speed.'],
        ], 1,
        'Die Sammlung prüft einen Normalfall und erkennbare Grenzen. Vorab definierte Kriterien machen das Urteil nachvollziehbar und verhindern, dass nur gelungene Beispiele zählen.',
        'This set checks a normal case and observable boundaries. Predefined criteria make the judgement auditable and prevent only successful examples from counting.'),
    ],
    feedback: L('Dein Observatorium erhält ein kleines Bot-Modell. Ein guter Forschungsablauf weiss auch, wann er keine Antwort hat.', 'Your observatory gains a small bot model. A sound research workflow also knows when it has no answer.'),
    reward: reward('audit-bot-model', 'Audit-Bot-Modell', 'Audit bot model'),
  },
  {
    ...draft, id: 'main-bachelor-capstone', type: 'main', stageId: '2',
    title: L('Das Bachelordach: eine eigene wissenschaftliche Entscheidung', 'The Bachelor roof: a scientific decision of your own'),
    description: L('Führe Quellenprüfung, Prozessdokumentation und begründeten Transfer in einem fiktiven Abschlussprojekt zusammen.', 'Bring source checking, process documentation and reasoned transfer together in a fictional capstone project.'),
    instructions: L('Du erstellst eine kleine Evidenzübersicht. KI darf Sortiervorschläge machen; du prüfst die Quellenkarten und verantwortest die Schlussfolgerung. Danach kommt eine neue Karte hinzu. Diese Spielaufgabe ist ein Zukunftsentwurf, keine Vorgabe zur Bachelorarbeit oder ihrer Bewertung.', 'You create a small evidence overview. AI may suggest categories; you check the source cards and take responsibility for the conclusion. Then a new card is added. This game task is a future design proposal, not a rule for the Bachelor thesis or its grading.'),
    moduleIds: ['BA', '102'], ...alignment('R4.3', 'K1.2'), prerequisiteQuestIds: ['main-methods-workshop'],
    worldLocation: 'bachelor-capstone', interaction: 'build-evidence-matrix-and-transfer', estimatedMinutes: 6,
    teachingPattern: 'documented-process-and-independent-transfer',
    questions: [
      Q('main-bachelor-capstone:q1',
        'In zehn fiktiven Studienkarten berichten drei einen positiven Zusammenhang, vier keinen und drei uneinheitliche Ergebnisse. Die KI schreibt: «Alle Studien zeigen einen positiven Zusammenhang.» Welche Überarbeitung ist wissenschaftlich nachvollziehbar?',
        'Of ten fictional study cards, three report a positive association, four report none and three report mixed findings. The AI writes: “All studies show a positive association.” Which revision is scientifically traceable?',
        [
          ['Nur die drei passenden Karten auflisten, ohne die Auswahl zu erklären.', 'List only the three matching cards without explaining the selection.'],
          ['Eine Evidenzmatrix mit allen berücksichtigten Karten, Auswahlkriterien, Designs, Ergebnissen und Grenzen erstellen und die gemischte Befundlage korrekt beschreiben.', 'Create an evidence matrix containing all included cards, selection criteria, designs, findings and limitations, and describe the mixed evidence accurately.'],
          ['«Alle» durch «viele» ersetzen und den Prüfprozess weglassen.', 'Replace “all” with “many” and omit the checking process.'],
        ], 1,
        'Der sichtbare Weg zur Schlussfolgerung ist Teil des wissenschaftlichen Produkts. Die Verteilung der Karten allein sagt noch nichts über Studienqualität oder Effektgrösse; die Matrix macht eine genauere Bewertung erst möglich.',
        'The visible route to the conclusion is part of the scientific product. The distribution of cards alone says nothing about study quality or effect size; the matrix enables a more detailed appraisal.'),
      Q('main-bachelor-capstone:q2',
        'Eine neue Karte untersucht dasselbe Thema mit anderer Stichprobe und anderem Messinstrument. Sie widerspricht deinem bisherigen Fazit. Welche Reaktion zeigt eigenständigen Transfer?',
        'A new card examines the same topic with a different sample and measure. It contradicts your earlier conclusion. Which response demonstrates independent transfer?',
        [
          ['Prüfen, ob Fragestellung und Messung vergleichbar sind, die neue Evidenz gewichten und das Fazit bei Bedarf begründet einschränken.', 'Check whether the question and measure are comparable, weigh the new evidence and qualify the conclusion with reasons if needed.'],
          ['Das Fazit automatisch umkehren, weil neue Studien grundsätzlich besser sind.', 'Automatically reverse the conclusion because newer studies are always better.'],
          ['Die Karte ignorieren, damit das fertige Produkt unverändert bleibt.', 'Ignore the card so the finished product stays unchanged.'],
        ], 0,
        'Transfer bedeutet hier, deine Kriterien auf neue Information anzuwenden. Eine wissenschaftliche Entscheidung darf sich ändern; entscheidend sind Vergleichbarkeit, Evidenz und eine nachvollziehbare Begründung.',
        'Transfer here means applying your criteria to new information. A scientific decision can change; comparability, evidence and a traceable justification matter.'),
    ],
    feedback: L('Dein Bachelordach erhält ein Forschungsfenster. Das Projekt verbindet nachvollziehbare Arbeit mit einer eigenen Antwort auf neue Evidenz.', 'Your Bachelor roof gains a research window. The project connects traceable work with your own response to new evidence.'),
    reward: reward('bachelor-research-window', 'Forschungsfenster', 'Research window'),
  },
];
