const L=(de,en)=>({de,en});
const lens=(id,de,en,criterionIds,contextIds,descriptionDe,descriptionEn)=>({id,title:L(de,en),criterionIds,competencyIds:[...new Set(criterionIds.map(x=>x.split('.')[0]))],contextIds,description:L(descriptionDe,descriptionEn)});
export const futureLenses=[
  lens('initiative','Eigeninitiative und Umsetzung','Initiative and implementation',['H2.1','H2.3','V2.2'],['without-ai','with-ai'],'Ein offenes Praxisproblem in ein begründetes Vorhaben übersetzen und die nächsten Schritte selbst organisieren.','Turn an open practice problem into a justified project and organise the next steps independently.'),
  lens('system-design','Systemgestaltung','System design',['T1.1','T3.1','T3.2','T3.3'],['with-ai','about-ai'],'Einen Forschungsablauf mit menschlichen und KI-gestützten Schritten entwerfen, testen und bei Ausfällen beherrschbar halten.','Design and test a research workflow with human and AI-assisted steps, keeping failures manageable.'),
  lens('creative-problem-solving','Kreative Problemlösung','Creative problem solving',['R1.1','H2.2'],['without-ai','with-ai'],'Für eine bisher ungelöste Versorgungs- oder Forschungsfrage mehrere eigene Lösungsansätze entwickeln, bevor ein Werkzeug Vorschläge macht.','Develop several personal approaches to an unresolved care or research question before consulting tool suggestions.'),
  lens('digital-critique','Kritische digitale Kompetenz','Critical digital competence',['T1.3','R4.2','V1.2'],['with-ai','about-ai'],'Technische Eignung, fachliche Aussagekraft und ethische Zulässigkeit eines Systems anhand dreier unterschiedlicher Kriterien prüfen.','Examine a system’s technical suitability, evidential value and ethical acceptability using three distinct criteria.'),
  lens('decisions-under-uncertainty','Entscheiden unter Unsicherheit','Decision-making under uncertainty',['R4.3','H1.3','V1.2'],['without-ai','with-ai'],'Trotz widersprüchlicher Befunde eine begrenzte Entscheidung begründen und angeben, welche neue Information sie ändern würde.','Justify a bounded decision despite conflicting findings and state what new information would change it.'),
  lens('self-efficacy','Selbstwirksamkeit reflektieren','Reflect on self-efficacy',['V2.1'],['without-ai','with-ai'],'Eigene Zuversicht mit konkreten Arbeitserfahrungen abgleichen. Das Selbsturteil bleibt von einem Kompetenznachweis getrennt.','Compare personal confidence with concrete work experiences. Keep self-report separate from evidence of competence.'),
  lens('critical-thinking','Kritisches Denken','Critical thinking',['P1.2','R2.2','R3.2','R4.1','R4.2','R4.3'],['without-ai','with-ai','about-ai'],'Annahmen und Alternativen bei Theorien, Messungen und Analysen begründet prüfen. Menschliche und generierte Behauptungen erfüllen dieselben fachlichen Beleganforderungen; beurteilt wird jeweils das zuständige Kriterium.','Examine assumptions and alternatives in theories, measurement and analysis with justification. Human and generated claims face the same evidential standards; assessment uses the relevant criterion in each case.'),
  lens('active-control','Aktive Steuerung','Active control',['T2.1','T2.2','T2.3','T3.3','V2.2','V2.3'],['with-ai'],'Bei einem KI-gestützten Projekt eigene Ziele setzen, Informationslast begrenzen und festlegen, wann selbst gerechnet, entschieden oder Unterstützung eingeholt wird; Werkzeuge dafür gezielt einstellen.','Set personal goals, manage information load and decide when to calculate, decide or seek help personally in an AI-assisted project; adjust tools accordingly.'),
  lens('self-determination','Selbstbestimmung','Self-determination',['V1.3','V2.1'],['without-ai','with-ai'],'Den Einsatz oder bewussten Verzicht auf KI anhand eigener Ziele, Schutzinteressen und professioneller Grenzen begründen.','Justify using or declining AI through personal goals, protected interests and professional limits.'),
  lens('ethics','Ethisches Urteilen','Ethical judgement',['V1.1','V1.2','V1.3'],['without-ai','with-ai','about-ai'],'Zielkonflikte zwischen individueller Unterstützung, Fairness und Datenschutz an einem fiktiven KI-System bearbeiten.','Address competing aims of individual support, fairness and privacy in a fictional AI system.'),
  lens('cooperation','Kooperation','Cooperation',['K3.1','K3.2','K3.3'],['without-ai','with-ai'],'Verantwortung in einem interdisziplinären Team mit KI-Werkzeugen so verteilen, dass Übergaben und menschliche Entscheidungen nachvollziehbar bleiben.','Allocate responsibility in an interdisciplinary team using AI so that handovers and human decisions remain traceable.'),
  lens('communication','Kommunikation','Communication',['K1.1','K1.2','K1.3','K2.2'],['without-ai','with-ai','about-ai'],'Ein unsicheres Forschungsergebnis und die Rolle der KI unterschiedlichen Beteiligten erklären; abweichende Sichtweisen aufnehmen und Missverständnisse klären.','Explain an uncertain research finding and the role of AI to different participants; engage with differing views and clarify misunderstandings.'),
  lens('systems-thinking','In Zusammenhängen denken','Systems thinking',['P2.1','P2.3','H2.3'],['without-ai','with-ai','about-ai'],'Bei einer Veränderung Rückwirkungen zwischen Person, Institution und technischem System berücksichtigen.','Consider feedback between people, institutions and technical systems when planning change.'),
  lens('adaptive-learning','Lernen bei technologischem Wandel','Learning amid technological change',['T1.3','V2.1','V2.2','V2.3'],['without-ai','with-ai','about-ai'],'Ein unbekanntes Werkzeug anhand stabiler Fachkriterien erschliessen und eigene Wissenslücken gezielt bearbeiten.','Learn an unfamiliar tool through stable disciplinary criteria and address personal knowledge gaps.')
];
export const futureCoverageRule=L('Diese Bezüge machen Future Skills sichtbar. Sie sind keine weiteren Kompetenzskalen: Ein Kriterium kann in mehreren thematischen Ansichten erscheinen, wird aber nur an seinem kanonischen Ort erfasst. Die ersten zwölf Bezüge orientieren sich an AIComp; die letzten zwei machen zusätzliche Zukunftsfragen ausdrücklich sichtbar.','These links make future skills visible. They are not additional competence scales: a criterion may appear in several thematic views but is recorded only in its canonical location. The first twelve links draw on AIComp; the final two make further future-oriented questions explicit.');
export const futureDesignTests=[
  L('Bleibt das Lernziel sinnvoll, wenn das heute verwendete KI-Werkzeug ersetzt wird?','Does the objective remain useful if today’s AI tool is replaced?'),
  L('Müssen Studierende selbst eine Frage, Alternative oder begründete Entscheidung entwickeln?','Must students develop a question, alternative or justified decision themselves?'),
  L('Wird erkennbar, wo KI unterstützt und welche fachliche Eigenleistung bestehen bleibt?','Is it clear where AI assists and which disciplinary work remains the student’s own?'),
  L('Werden Unsicherheit, Systemfolgen und die Perspektive betroffener Menschen berücksichtigt?','Does the task account for uncertainty, system effects and the perspectives of affected people?'),
  L('Verändert eine Rückmeldung das weitere Handeln, statt nur Punkte zu liefern?','Does feedback change subsequent action rather than merely award points?'),
  L('Ist der neue Lernanteil in den vorhandenen Arbeitsaufwand integriert und einer konkreten bisherigen Aktivität zugeordnet?','Is the new learning component integrated into the existing workload and tied to a specific previous activity?')
];
